use hex::{FromHex, ToHex}; // to pretty print hash
use serde::{Deserialize, Serialize};
use serde_json;
use std::env;
use std::time::SystemTime;

use secp256k1::{Message, PublicKey, Secp256k1, SecretKey};
use sha2::{self, Digest};

#[derive(Serialize, Deserialize, Debug)]
struct Position {
    latitude: f64,
    longitude: f64,
    timestamp: u64,
}

#[derive(Serialize, Deserialize, Debug)]
struct SignedPosition {
    position: Position,
    signature: String,
    public_key: String,
}

fn main() {
    let args = env::args().collect::<Vec<String>>();
    let _program = args[0].clone();

    if args.len() != 4 {
        eprintln!("Usage: {} <latitude> <longitude> <secret_key>", _program);
        return;
    }

    let latitude = args[1].parse::<f64>().expect("Invalid latitude");
    let longitude = args[2].parse::<f64>().expect("Invalid longitude");
    let secret_key_hex = &args[3];

    sign_coordinates(latitude, longitude);
}

#[no_mangle]
fn sign_coordinates(latitude: f64, longitude: f64) {
    // let secret_key = hex::decode(secret_key_hex).expect("Invalid hex");
    // let secret_key_slice = secret_key.as_slice();
    let secret_key_slice = [1 as u8; 32].as_ref();

    // get current timestamp
    let timestamp: u64 = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .expect("Time went backwards")
        .as_secs();

    // build Position object
    let position = Position {
        latitude,
        longitude,
        timestamp,
    };
    // println!(
    //     "Built position object, using coordinates sent as params, as well as current timestamp"
    // );
    // println!("Position: {:#?}", position);

    // serialize both for hashing purpose
    let payload = serde_json::to_string(&position).expect("JSON serialization");

    // hash payload
    let result = hash_message(&payload);
    let hash = result.as_ref();
    // println!("Position object's hash: {}\n", hash.encode_hex::<String>());

    // get key pair from secret key passed in arguments
    let (secret_key, public_key) = create_key_pair_from_bytes(secret_key_slice);

    // sign result
    let sig = sign_hash_slice(&secret_key, hash);
    // println!(
    //     "Signed position object's hash using the key pair generated by private key given in params"
    // );
    // println!("Signature: {:?}\n", sig);

    // serialize signature and public key - needed as ecdsa::Signature does not implement Serialize
    let serialized_signature = sig.serialize_compact().encode_hex::<String>();
    let serialized_public_key = public_key.serialize().encode_hex::<String>();

    // build SignedPosition object, to be sent
    let signed_position = SignedPosition {
        position,
        signature: serialized_signature,
        public_key: serialized_public_key,
    };
    // println!(
    //     "Built a SignedPosition object, containing the position object, signature and public key\nThis object can be serialized and sent to other party for verification\n"
    // );
    // println!("SignedPosition: {:#?}\n", signed_position);

    // serialize SignedPosition object
    let signed_payload = serde_json::to_string(&signed_position).expect("JSON serialization");

    /*
     * Here the SignedPosition object would be sent to another party
     */
    // fs::write("out/out.json", &signed_payload).expect("Unable to write file");
}

fn create_key_pair_from_bytes(secret_bytes: &[u8]) -> (SecretKey, PublicKey) {
    let secp = Secp256k1::new();
    let secret_key = SecretKey::from_slice(secret_bytes).expect("32 bytes");
    let public_key = PublicKey::from_secret_key(&secp, &secret_key);
    (secret_key, public_key)
}

fn hash_message(message: &str) -> Box<[u8]> {
    let mut hasher = sha2::Sha256::new();
    hasher.update(message.as_bytes());
    hasher.finalize().as_slice().into()
}

fn sign_hash_slice(secret_key: &SecretKey, hash: &[u8]) -> secp256k1::ecdsa::Signature {
    let message = Message::from_digest_slice(&hash).expect("32 bytes");
    let secp = Secp256k1::new();
    secp.sign_ecdsa(&message, &secret_key)
}

fn verify_signature(
    public_key: &PublicKey,
    sig: &secp256k1::ecdsa::Signature,
    hash: &[u8],
) -> bool {
    let secp = Secp256k1::new();
    let message = Message::from_digest_slice(&hash).expect("32 bytes");
    secp.verify_ecdsa(&message, &sig, &public_key).is_ok()
}

fn deser_pubkey(pubkey_str: &str) -> PublicKey {
    PublicKey::from_slice(<[u8; 33]>::from_hex(&pubkey_str).unwrap().as_ref()).expect("33 bytes")
}
